name: Deploy to Kubernetes

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Apply Namespace
        run: kubectl apply -f k8s/namespace.yaml || true

      - name: Deploy App
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Rollout
        run: kubectl rollout status deployment/credit-report-web -n credit-reporting
